# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS_PDF_TEST' do
  # Pods for iOS_PDF_TEST
    pod 'SSZipArchive', '2.1.4'
    pod 'MIHCrypto', '~> 0.4.0'
    pod 'UICKeyChainStore'
    pod 'YYCache'
    pod 'YYModel'
    pod 'YYText'
    pod 'Masonry'
    pod 'MBProgressHUD'
    pod 'libwebp', '1.0.0'
    pod 'MJRefresh'

end
